version: 2
jobs:
  build:
    docker:
      - image: kvaes/docker-powershell-azure
    steps:
      - checkout
      - run: 
          name: Install things we need
          command: 'powershell -File ./tools/test.ps1'          
          
    - run:
          name: Powershell
          command: 'powershell Get-Module -Name AzureRM* -ListAvailable '
            
        
             
            
       
     
             



            
         
