version: 2

jobs:

  build:

    docker:

      # specify the version you desire here

      - image: buildpack-deps:latest

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |

            uname -srm
            
            cat /etc/issue
            # Install system components
sudo apt-get update
sudo apt-get install curl gnupg apt-transport-https

# Import the public repository GPG keys
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Register the Microsoft Product feed
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'

# Update the list of products
sudo apt-get update

# Install PowerShell
sudo apt-get install -y powershell

# Start PowerShell
pwsh
            
         
