version: 2
jobs:
  build:
    docker:
       - image: microsoft.com/windows/servercore:1809_amd64

    steps:
      - checkout

      - run:
          name: Greeting
          command: dir

      - run:
          name: Print the Current Time
          command: date
	
      
