version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: kvaes/docker-powershell-azure
     # - image: twitchax/azure-powershell-core
       
  
      
 
            
        
             
            
       
     
             



            
         
