
version: 2.0

jobs:
  build: # name of your job
    docker: # executor type
      - image: buildpack-deps:trusty

        steps:

            - checkout

            - run:

                name: Run build script
