version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: microsoft/azure-cli

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |
           
           
 
            uname -srm            
            cat /etc/issue
            #apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

            #pwsh -File  ./tools/first.ps1
            pwsh -Version
            #pwsh -WorkingDirectory ~/tools
            pwd
            ls -l
            cd tools
            ls -l
            pwd
            pwsh test.ps1
            #pwsh Install-Module -Name AzureRM -RequiredVersion 2.4.0 -Repository PSGallery -Force
       
     
             



            
         
