version: 2
jobs:
  build:
    docker:
       - image: mcr.microsoft.com/windows/servercore:ltsc2019

    steps:
      - checkout

      - run:
          name: Greeting
          command: dir

      - run:
          name: Print the Current Time
          command: date
	
      
