version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: kvaes/docker-powershell-azure

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |
           
           
 
            uname -srm            
            cat /etc/issue
            #apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

            #pwsh -File  ./tools/first.ps1
           
            #pwsh -WorkingDirectory ~/tools
            pwd
            ls -l
            cd tools
            ls -l
            pwd
           powershell get-command *azure*”
        
             
             #az login -u sdey@tollplus.com -p satyam1$2$3
            #pwsh Install-Module -Name AzureRM -RequiredVersion 2.4.0 -Repository PSGallery -Force
       
     
             



            
         
