version: 2
jobs:
  build:
    docker:
      - image: kvaes/docker-powershell-azure
    steps:
      - checkout
      #- run: 
         # name: Install things we need
         # command: 'powershell -File ./tools/test.ps1'          
      - run:
          name: Powershell
          command: 'powershell Get-Module -Name AzureRM* -ListAvailable '
      - run:
          name: Git1
          command: |
                    apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
                    sudo apt-get update
                    sudo apt-get install -y git
                    mkdir ~/project/replica1
                    cd ./docker
                    cp  -r . ~/project/replica1
                    cd ~/project/replica1
                     ls
                    pwd
                    #git config –-global user.name “Test”
                    #git config –-global user.email “sdey@tollplus.com”
                    git init
                    git add *
                    git commit -a -m "hello"
                    git remote rm origin
                    git remote add myserver ssh:ssh://sdey@github.com/sdeytollplus/TestVSTS.git
                    git push myserver 
                    
               
            
        
             
            
       
     
             



            
         
