
version: 1.0

jobs:
  build: 
    machine: 
      image: circleci/classic:201708-01 # VM will run Ubuntu 14.04 for this release da
      steps:

            - checkout

            - run:

                name: Run build script
