version: 2

jobs:

  build:

    docker:

      # specify the version you desire here

      - image: buildpack-deps:latest

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |

            uname -srm
            
            cat /etc/issue
            
            sudo dpkg -i powershell_6.1.0-1.ubuntu.18.04_amd64.deb
            sudo apt-get install -f
            pwsh

