version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: kvaes/docker-powershell-azure
       

    steps:

      - checkout

      - run:

          name: Install things we need

          command: 'powershell -File ./tools/test.ps1' 
          
      - run:

          name: Powershell

          command: 'powershell Get-Module Azure* -list '
       - run:

          name: Powershell-1   
          command: 'powershell Import-Module AzureRM.NetCore.Preview '
          
        - run:

          name: Powershel2  
          command: 'powershell Login-AzureRMAccount '

                    
           
           
 
            
        
             
            
       
     
             



            
         
