version: 2
jobs:
  build:
    docker:
      - image: kvaes/docker-powershell-azure
    steps:
      - checkout
      - run: echo "A first hello"
  
            
        
             
            
       
     
             



            
         
