version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: kvaes/docker-powershell-azure
     # - image: twitchax/azure-powershell-core
       

    steps:

      - checkout

      - run:

          name: Install things we need
          command: |
          cat /etc/issue
          apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
          sudo apt-get install -y git
          sudo git clone https://coditapi.scm.azure-api.net/
         # command: 'powershell -File ./tools/test.ps1' 
          
      - run:

          name: Powershell

          command: 'powershell Get-Module -Name AzureRM* -ListAvailable '
      
           
           
 
            
        
             
            
       
     
             



            
         
