version: 2

jobs:

  build:

    docker:

      # specify the version you desire here

      - image: buildpack-deps:disco

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |

            uname -srm
            
            cat /etc/issue
            # Install system components
      
   



            
         
