version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: kvaes/docker-powershell-azure

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |
           
           
 
            
        
             
             #az login -u sdey@tollplus.com -p satyam1$2$3
            #pwsh Install-Module -Name AzureRM -RequiredVersion 2.4.0 -Repository PSGallery -Force
       
     
             



            
         
