version: 2

jobs:

  build:
  
    
    docker:

      # specify the version you desire here

      - image: mcr.microsoft.com/powershell:preview

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |
           
           
 
            uname -srm            
            cat /etc/issue
            apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

            #pwsh -File  ./tools/first.ps1
            pwsh -Version
            #pwsh -WorkingDirectory ~/tools
            pwd
            
      - run:
          name: "What was my custom environment variable1"    
            command: echo $CIRCLE_WORKING_DIRECTORY
            
        - run:
          name: "What was my custom environment variable2"    
            command: echo $HOME
         
     
             



            
         
