version: 2

jobs:

  build:

    docker:

      # specify the version you desire here

      - image: buildpack-deps:xenial

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |

            uname -srm            
            cat /etc/issue
            apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
            wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb

            # Update the list of products
            sudo apt-get update

            # Install PowerShell
            sudo apt-get install -y powershell
   



            
         
