version: 2

jobs:

  build:
   working_directory: ~/tools
    docker:

      # specify the version you desire here

      - image: mcr.microsoft.com/powershell:preview

        

    steps:

      - checkout

      - run:

          name: Install things we need

          command: |

            uname -srm            
            cat /etc/issue
            apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
            #!/bin/bash
            pwsh ./first.ps1
            
     
             



            
         
