version: 2
jobs:
  build:
    docker:
      - image: microsoft/powershell@sha256:6d36c498c1fdbb3ef42acabea1d06b12870e390fd3053993974ebaa6ba507849

    steps:
      - checkout

      - run:
          name: Greeting
          command: dir

      - run:
          name: Print the Current Time
          command: date

     - run:
         name: Run build script
         command: 'powershell -File ./tools/test.ps1'